version: '3.9'
services:
  api:
    build: ./API
    restart: on-failure
    ports:
      - "8001:8001"
      - "9001:9001"
    volumes:
      - ./API:/api
    env_file:
      - .env

  longpoll:
    build: ./Longpoll
    restart: on-failure
    ports:
      - "8002:8002"
      - "9002:9002"
    volumes:
      - ./Longpoll:/longpoll
    env_file:
      - .env

  telegram-bot:
    build: ./Telegram-Bot
    restart: on-failure
    ports:
      - "9003:9003"
    volumes:
      - ./Telegram-Bot:/tg-bot
    depends_on:
      - api
      - longpoll
    env_file:
      - .env